//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalitte.RiskManagement.Web.Pages.Shared.User {
    
    
    public partial class edit {
        
        /// <summary>
        /// entityWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTWindow entityWindow;
        
        /// <summary>
        /// ctlTabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTTabPanel ctlTabs;
        
        /// <summary>
        /// ctlGenForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTFormPanel ctlGenForm;
        
        /// <summary>
        /// ctlLockedLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Label ctlLockedLabel;
        
        /// <summary>
        /// ctlUsername control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTUsernameField ctlUsername;
        
        /// <summary>
        /// ctlPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTTextField ctlPassword;
        
        /// <summary>
        /// ctlAd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTTextField ctlAd;
        
        /// <summary>
        /// ctlSoyad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTTextField ctlSoyad;
        
        /// <summary>
        /// ctlEMail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTEmailField ctlEMail;
        
        /// <summary>
        /// ctlEnabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTCheckBox ctlEnabled;
        
        /// <summary>
        /// ctlBirim control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTAutoComplete ctlBirim;
        
        /// <summary>
        /// ctlUnvan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTAutoComplete ctlUnvan;
        
        /// <summary>
        /// TTPanel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTPanel TTPanel2;
        
        /// <summary>
        /// TTFormPanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTFormPanel TTFormPanel1;
        
        /// <summary>
        /// TTCompositeField1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTCompositeField TTCompositeField1;
        
        /// <summary>
        /// ctlRoles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTComboBox ctlRoles;
        
        /// <summary>
        /// TTButton2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTButton TTButton2;
        
        /// <summary>
        /// ctlCurrentRolesGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTGrid ctlCurrentRolesGrid;
        
        /// <summary>
        /// TTStore2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTStore TTStore2;
        
        /// <summary>
        /// ctlUnlockBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTCmdButon ctlUnlockBtn;
        
        /// <summary>
        /// ctlSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTCmdButon ctlSave;
        
        /// <summary>
        /// TTButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTButton TTButton1;
    }
}
