//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalitte.BI.Shared.ParametersService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemParameterInfo", Namespace="http://schemas.datacontract.org/2004/07/Kalitte.BI.ServerPlatform.Entities")]
    [System.SerializableAttribute()]
    public partial class SystemParameterInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DecisionSupportBrowserWinUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortalUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DecisionSupportBrowserWinUrl {
            get {
                return this.DecisionSupportBrowserWinUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.DecisionSupportBrowserWinUrlField, value) != true)) {
                    this.DecisionSupportBrowserWinUrlField = value;
                    this.RaisePropertyChanged("DecisionSupportBrowserWinUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortalUrl {
            get {
                return this.PortalUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PortalUrlField, value) != true)) {
                    this.PortalUrlField = value;
                    this.RaisePropertyChanged("PortalUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ParametersService.IParametersService")]
    public interface IParametersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametersService/GetParameters", ReplyAction="http://tempuri.org/IParametersService/GetParametersResponse")]
        Kalitte.BI.Shared.ParametersService.SystemParameterInfo GetParameters();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParametersServiceChannel : Kalitte.BI.Shared.ParametersService.IParametersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParametersServiceClient : System.ServiceModel.ClientBase<Kalitte.BI.Shared.ParametersService.IParametersService>, Kalitte.BI.Shared.ParametersService.IParametersService {
        
        public ParametersServiceClient() {
        }
        
        public ParametersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParametersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParametersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParametersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Kalitte.BI.Shared.ParametersService.SystemParameterInfo GetParameters() {
            return base.Channel.GetParameters();
        }
    }
}
