//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalitte.RiskManagement.Web.UI.Pages.Management.Soru {
    
    
    public partial class edit {
        
        /// <summary>
        /// ctlAnswerEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Web.UI.Pages.Management.Soru.cevapedit ctlAnswerEditor;
        
        /// <summary>
        /// entityWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTWindow entityWindow;
        
        /// <summary>
        /// ctlTabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTTabPanel ctlTabs;
        
        /// <summary>
        /// TTPanel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTPanel TTPanel2;
        
        /// <summary>
        /// ctlGenForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTFormPanel ctlGenForm;
        
        /// <summary>
        /// ctlGroupId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTComboBox ctlGroupId;
        
        /// <summary>
        /// TTStore1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTStore TTStore1;
        
        /// <summary>
        /// ctlAd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTTextField ctlAd;
        
        /// <summary>
        /// ctlAktif control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTEnumCombo ctlAktif;
        
        /// <summary>
        /// ctlZorunluluk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTEnumCombo ctlZorunluluk;
        
        /// <summary>
        /// ctlKatsayi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTNumberField ctlKatsayi;
        
        /// <summary>
        /// ctlAciklama control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTTextArea ctlAciklama;
        
        /// <summary>
        /// ctlCurrentAnswersGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTGrid ctlCurrentAnswersGrid;
        
        /// <summary>
        /// Toolbar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Toolbar Toolbar1;
        
        /// <summary>
        /// ctlAddBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTCmdButon ctlAddBtn;
        
        /// <summary>
        /// ctlEditBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTCmdButon ctlEditBtn;
        
        /// <summary>
        /// TTStore2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTStore TTStore2;
        
        /// <summary>
        /// ctlSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTCmdButon ctlSave;
        
        /// <summary>
        /// TTButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTButton TTButton1;
    }
}
