//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalitte.RiskManagement.Web.Pages.Risk {
    
    
    public partial class questionlist {
        
        /// <summary>
        /// dsMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTStore dsMain;
        
        /// <summary>
        /// ctlMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Label ctlMessage;
        
        /// <summary>
        /// grid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTGrid grid;
        
        /// <summary>
        /// GroupingView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.GroupingView GroupingView1;
        
        /// <summary>
        /// RowSelectionModel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.RowSelectionModel RowSelectionModel1;
        
        /// <summary>
        /// ctlAnswerPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTPanel ctlAnswerPanel;
        
        /// <summary>
        /// ctlPrevQuestion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTCmdButon ctlPrevQuestion;
        
        /// <summary>
        /// TTCmdButon2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTCmdButon TTCmdButon2;
        
        /// <summary>
        /// ctlQuestionInfoPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTPanel ctlQuestionInfoPanel;
        
        /// <summary>
        /// ctlGroupName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Label ctlGroupName;
        
        /// <summary>
        /// ctlQuestionName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Label ctlQuestionName;
        
        /// <summary>
        /// ctlAnswerGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTGrid ctlAnswerGrid;
        
        /// <summary>
        /// Toolbar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Toolbar Toolbar1;
        
        /// <summary>
        /// ctlNextQuestion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTCmdButon ctlNextQuestion;
    }
}
