//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalitte.BI.Shared.AnalyticsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModuleInfo", Namespace="http://schemas.datacontract.org/2004/07/Kalitte.BI.ServerPlatform.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.FilterSelectData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.DataSelectType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.UserReport[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.UserReport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.ModuleInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.DashboardInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.DashboardInfo))]
    public partial class ModuleInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivatorInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivatorInfo {
            get {
                return this.ActivatorInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivatorInfoField, value) != true)) {
                    this.ActivatorInfoField = value;
                    this.RaisePropertyChanged("ActivatorInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImageIndex {
            get {
                return this.ImageIndexField;
            }
            set {
                if ((this.ImageIndexField.Equals(value) != true)) {
                    this.ImageIndexField = value;
                    this.RaisePropertyChanged("ImageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleName {
            get {
                return this.ModuleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleNameField, value) != true)) {
                    this.ModuleNameField = value;
                    this.RaisePropertyChanged("ModuleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterSelectData", Namespace="http://schemas.datacontract.org/2004/07/Kalitte.BI.Shared")]
    [System.SerializableAttribute()]
    public partial class FilterSelectData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilterTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> FiltersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] IDListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Kalitte.BI.Shared.AnalyticsService.DataSelectType SelectTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationUrl {
            get {
                return this.DestinationUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationUrlField, value) != true)) {
                    this.DestinationUrlField = value;
                    this.RaisePropertyChanged("DestinationUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilterType {
            get {
                return this.FilterTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FilterTypeField, value) != true)) {
                    this.FilterTypeField = value;
                    this.RaisePropertyChanged("FilterType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Filters {
            get {
                return this.FiltersField;
            }
            set {
                if ((object.ReferenceEquals(this.FiltersField, value) != true)) {
                    this.FiltersField = value;
                    this.RaisePropertyChanged("Filters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] IDList {
            get {
                return this.IDListField;
            }
            set {
                if ((object.ReferenceEquals(this.IDListField, value) != true)) {
                    this.IDListField = value;
                    this.RaisePropertyChanged("IDList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Key {
            get {
                return this.KeyField;
            }
            set {
                if ((this.KeyField.Equals(value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Kalitte.BI.Shared.AnalyticsService.DataSelectType SelectType {
            get {
                return this.SelectTypeField;
            }
            set {
                if ((this.SelectTypeField.Equals(value) != true)) {
                    this.SelectTypeField = value;
                    this.RaisePropertyChanged("SelectType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSelectType", Namespace="http://schemas.datacontract.org/2004/07/Kalitte.BI.Shared")]
    public enum DataSelectType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ID = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IDList = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserReport", Namespace="http://schemas.datacontract.org/2004/07/Kalitte.BI.Shared")]
    [System.SerializableAttribute()]
    public partial class UserReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CreationDatek__BackingFieldField;
        
        private int ReportIdk__BackingFieldField;
        
        private string ReportNamek__BackingFieldField;
        
        private string ReportTypek__BackingFieldField;
        
        private string UserNamek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CreationDate>k__BackingField", IsRequired=true)]
        public string CreationDatek__BackingField {
            get {
                return this.CreationDatek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CreationDatek__BackingFieldField, value) != true)) {
                    this.CreationDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("CreationDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ReportId>k__BackingField", IsRequired=true)]
        public int ReportIdk__BackingField {
            get {
                return this.ReportIdk__BackingFieldField;
            }
            set {
                if ((this.ReportIdk__BackingFieldField.Equals(value) != true)) {
                    this.ReportIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("ReportIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ReportName>k__BackingField", IsRequired=true)]
        public string ReportNamek__BackingField {
            get {
                return this.ReportNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportNamek__BackingFieldField, value) != true)) {
                    this.ReportNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("ReportNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ReportType>k__BackingField", IsRequired=true)]
        public string ReportTypek__BackingField {
            get {
                return this.ReportTypek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportTypek__BackingFieldField, value) != true)) {
                    this.ReportTypek__BackingFieldField = value;
                    this.RaisePropertyChanged("ReportTypek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserName>k__BackingField", IsRequired=true)]
        public string UserNamek__BackingField {
            get {
                return this.UserNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNamek__BackingFieldField, value) != true)) {
                    this.UserNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("UserNamek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DashboardInfo", Namespace="http://schemas.datacontract.org/2004/07/Kalitte.BI.ServerPlatform.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.FilterSelectData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.DataSelectType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.UserReport[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.UserReport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.ModuleInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.ModuleInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.DashboardInfo[]))]
    public partial class DashboardInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AnalyticsService.IAnalyticsService")]
    public interface IAnalyticsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnalyticsService/GetModules", ReplyAction="http://tempuri.org/IAnalyticsService/GetModulesResponse")]
        Kalitte.BI.Shared.AnalyticsService.ModuleInfo[] GetModules();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnalyticsService/GetModuleDataAsArray", ReplyAction="http://tempuri.org/IAnalyticsService/GetModuleDataAsArrayResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.FilterSelectData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.DataSelectType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.UserReport[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.UserReport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.ModuleInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.ModuleInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.DashboardInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.DashboardInfo))]
        byte[] GetModuleDataAsArray(object moduleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnalyticsService/GetModuleData", ReplyAction="http://tempuri.org/IAnalyticsService/GetModuleDataResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.FilterSelectData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.DataSelectType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.UserReport[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.UserReport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.ModuleInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.ModuleInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.DashboardInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Kalitte.BI.Shared.AnalyticsService.DashboardInfo))]
        System.Data.DataSet GetModuleData(object moduleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnalyticsService/ValidateUsernamePassword", ReplyAction="http://tempuri.org/IAnalyticsService/ValidateUsernamePasswordResponse")]
        void ValidateUsernamePassword(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnalyticsService/GetUserDashboards", ReplyAction="http://tempuri.org/IAnalyticsService/GetUserDashboardsResponse")]
        Kalitte.BI.Shared.AnalyticsService.DashboardInfo[] GetUserDashboards();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnalyticsService/GetFilterData", ReplyAction="http://tempuri.org/IAnalyticsService/GetFilterDataResponse")]
        System.Data.DataSet GetFilterData(Kalitte.BI.Shared.AnalyticsService.FilterSelectData filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnalyticsService/SaveUserReport", ReplyAction="http://tempuri.org/IAnalyticsService/SaveUserReportResponse")]
        void SaveUserReport(string userName, string reportName, string reportype, byte[] reportData, string reportElement, bool saveAsTemplate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnalyticsService/GetUserReports", ReplyAction="http://tempuri.org/IAnalyticsService/GetUserReportsResponse")]
        Kalitte.BI.Shared.AnalyticsService.UserReport[] GetUserReports(string userName, string reportType, string reportElement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnalyticsService/GetReportDataByID", ReplyAction="http://tempuri.org/IAnalyticsService/GetReportDataByIDResponse")]
        byte[] GetReportDataByID(int reportid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnalyticsService/DeleteReportDataByID", ReplyAction="http://tempuri.org/IAnalyticsService/DeleteReportDataByIDResponse")]
        void DeleteReportDataByID(int reportid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAnalyticsServiceChannel : Kalitte.BI.Shared.AnalyticsService.IAnalyticsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnalyticsServiceClient : System.ServiceModel.ClientBase<Kalitte.BI.Shared.AnalyticsService.IAnalyticsService>, Kalitte.BI.Shared.AnalyticsService.IAnalyticsService {
        
        public AnalyticsServiceClient() {
        }
        
        public AnalyticsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnalyticsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalyticsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalyticsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Kalitte.BI.Shared.AnalyticsService.ModuleInfo[] GetModules() {
            return base.Channel.GetModules();
        }
        
        public byte[] GetModuleDataAsArray(object moduleId) {
            return base.Channel.GetModuleDataAsArray(moduleId);
        }
        
        public System.Data.DataSet GetModuleData(object moduleId) {
            return base.Channel.GetModuleData(moduleId);
        }
        
        public void ValidateUsernamePassword(string userName, string password) {
            base.Channel.ValidateUsernamePassword(userName, password);
        }
        
        public Kalitte.BI.Shared.AnalyticsService.DashboardInfo[] GetUserDashboards() {
            return base.Channel.GetUserDashboards();
        }
        
        public System.Data.DataSet GetFilterData(Kalitte.BI.Shared.AnalyticsService.FilterSelectData filter) {
            return base.Channel.GetFilterData(filter);
        }
        
        public void SaveUserReport(string userName, string reportName, string reportype, byte[] reportData, string reportElement, bool saveAsTemplate) {
            base.Channel.SaveUserReport(userName, reportName, reportype, reportData, reportElement, saveAsTemplate);
        }
        
        public Kalitte.BI.Shared.AnalyticsService.UserReport[] GetUserReports(string userName, string reportType, string reportElement) {
            return base.Channel.GetUserReports(userName, reportType, reportElement);
        }
        
        public byte[] GetReportDataByID(int reportid) {
            return base.Channel.GetReportDataByID(reportid);
        }
        
        public void DeleteReportDataByID(int reportid) {
            base.Channel.DeleteReportDataByID(reportid);
        }
    }
}
