//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalitte.RiskManagement.Web.UI.Pages.Management.RiskMatrisTanim {
    
    
    public partial class edit {
        
        /// <summary>
        /// entityWindow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTWindow entityWindow;
        
        /// <summary>
        /// ctlTabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTTabPanel ctlTabs;
        
        /// <summary>
        /// ctlGenForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTFormPanel ctlGenForm;
        
        /// <summary>
        /// ctlPuanBaslangic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTNumberField ctlPuanBaslangic;
        
        /// <summary>
        /// ctlPuanBitis control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTNumberField ctlPuanBitis;
        
        /// <summary>
        /// ctlGrupDeger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTTextField ctlGrupDeger;
        
        /// <summary>
        /// TTPanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTPanel TTPanel1;
        
        /// <summary>
        /// ColorPalette1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.ColorPalette ColorPalette1;
        
        /// <summary>
        /// ctlRenk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTTextArea ctlRenk;
        
        /// <summary>
        /// ctlSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTCmdButon ctlSave;
        
        /// <summary>
        /// TTButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Kalitte.RiskManagement.Framework.Controls.TTButton TTButton1;
    }
}
